
NemHealerAlertsSV = {
["empRegrowthEnabled"] = true,
["refoSoundName"] = "Redfox",
["atonTimerShown"] = true,
["castlbEnabled"] = true,
["enabled"] = true,
["fontName"] = "Gotham Narrow Ultra",
["y"] = 180,
["x"] = 0,
["refoEnabled"] = true,
["atonSoundName"] = "Bell",
["wgSoundEnabled"] = true,
["wgSoundName"] = "Lamp",
["fontSize"] = 25,
["point"] = "CENTER",
["scale"] = 1,
["lbSoundEnabled"] = true,
["flash"] = true,
["glowEnabled"] = true,
["wgEnabled"] = true,
["refoSoundEnabled"] = true,
["relativePoint"] = "CENTER",
["sotfEnabled"] = true,
["abundanceStackThreshold"] = 7,
["abundanceSoundEnabled"] = true,
["abundanceEnabled"] = true,
["relativeTo"] = "UIParent",
["sotfSoundEnabled"] = true,
["vsSoundName"] = "Ping",
["lbTimerShown"] = true,
["abundanceSoundName"] = "Lamp",
["lbEnabled"] = true,
["atonEnabled"] = true,
["ver"] = 5,
["lbSoundName"] = "Bell",
["vsEnabled"] = true,
["sotfSoundName"] = "Ping",
["atonSoundEnabled"] = true,
["alertColors"] = {
["refo"] = {
["b"] = 0.859,
["g"] = 0.596,
["r"] = 0.204,
},
["sotf"] = {
["b"] = 0.753,
["g"] = 0.898,
["r"] = 0,
},
["aton"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["vs"] = {
["b"] = 0.8,
["g"] = 0.2,
["r"] = 0.6,
},
["lb"] = {
["b"] = 0.282,
["g"] = 0.631,
["r"] = 0.141,
},
["wg"] = {
["b"] = 0.18,
["g"] = 0.886,
["r"] = 0.651,
},
["abundance"] = {
["r"] = 1,
["g"] = 0.82,
["b"] = 0,
},
["castlb"] = {
["r"] = 0.141,
["g"] = 0.631,
["b"] = 0.282,
},
},
["vsSoundEnabled"] = true,
["sotfTimerShown"] = true,
}
