
NemHealerAlertsSV = {
["pwsSoundEnabled"] = true,
["refoSoundName"] = "Redfox",
["atonTimerShown"] = true,
["castlbEnabled"] = true,
["enabled"] = true,
["envEnabled"] = true,
["sotfSoundEnabled"] = true,
["alertColors"] = {
["refo"] = {
["r"] = 0.204,
["g"] = 0.596,
["b"] = 0.859,
},
["rm"] = {
["b"] = 0.612,
["g"] = 1,
["r"] = 0,
},
["vs"] = {
["r"] = 0.6,
["g"] = 0.2,
["b"] = 0.8,
},
["lb"] = {
["r"] = 0.141,
["g"] = 0.631,
["b"] = 0.282,
},
["castlb"] = {
["b"] = 0.282,
["g"] = 0.631,
["r"] = 0.141,
},
["abundance"] = {
["b"] = 0,
["g"] = 0.82,
["r"] = 1,
},
["aton"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["env"] = {
["b"] = 0.714,
["g"] = 1,
["r"] = 0.992,
},
["wg"] = {
["r"] = 0.651,
["g"] = 0.886,
["b"] = 0.18,
},
["sotf"] = {
["r"] = 0,
["g"] = 0.898,
["b"] = 0.753,
},
["pws"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
["cufGlowEnabled"] = true,
["abundanceSoundName"] = "Lamp",
["fontName"] = "Gotham Narrow Ultra",
["sotfSoundName"] = "Ping",
["y"] = 180,
["atonSoundEnabled"] = true,
["refoEnabled"] = true,
["vsSoundEnabled"] = true,
["atonThresholdRaid"] = 4,
["rmSoundName"] = "Ping",
["atonSoundName"] = "Bell",
["wgSoundEnabled"] = true,
["wgSoundName"] = "Lamp",
["fontSize"] = 25,
["point"] = "CENTER",
["envSoundEnabled"] = true,
["scale"] = 1,
["lbSoundName"] = "Bell",
["lbSoundEnabled"] = true,
["flash"] = true,
["pwsSoundName"] = "Ping",
["wgEnabled"] = true,
["refoSoundEnabled"] = true,
["relativePoint"] = "CENTER",
["atonEnabled"] = true,
["sotfEnabled"] = true,
["envSoundName"] = "Bell",
["abundanceSoundEnabled"] = true,
["relativeTo"] = "UIParent",
["rmEnabled"] = true,
["lbTimerShown"] = true,
["vsSoundName"] = "Ping",
["abundanceEnabled"] = true,
["vsEnabled"] = true,
["atonThresholdDungeon"] = 2,
["lbEnabled"] = true,
["ver"] = 6,
["rmThresholdRaid"] = 4,
["abundanceStackThreshold"] = 7,
["pwsEnabled"] = true,
["x"] = 0,
["rmThresholdDungeon"] = 2,
["rmSoundEnabled"] = true,
["sotfTimerShown"] = true,
}
