
AbilityTimeline = {
["profileKeys"] = {
["Corzumo - Draenor"] = "Default",
["Nothree - Draenor"] = "Default",
["Corzumo - Stormrage"] = "Default",
["Abaray - Draenor"] = "Default",
["Unlockit - Draenor"] = "Default",
["Corry - Draenor"] = "Default",
["Cooriam - Draenor"] = "Default",
["Altoki - Draenor"] = "Default",
["Sedore - Draenor"] = "Default",
["Corzos - Draenor"] = "Default",
["Corwing - Draenor"] = "Default",
["Coorlan - Draenor"] = "Default",
["Corra - Draenor"] = "Default",
["Gembank - Stormrage"] = "Default",
["Faile - Stormrage"] = "Default",
["Decoran - Draenor"] = "Default",
["Corpy - Draenor"] = "Default",
},
["global"] = {
["text_highlight_frame"] = {
["Modern"] = {
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
},
["Coor_2027"] = {
["y"] = -264.5,
["x"] = -11.99896240234375,
["point"] = "TOP",
},
["2026_quazii"] = {
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
},
["Resto"] = {
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
},
},
["bigicon"] = {
["Modern"] = {
["margin"] = 10,
["grow_direction"] = "RIGHT",
},
["Coor_2027"] = {
["margin"] = 10,
["grow_direction"] = "RIGHT",
},
["2026_quazii"] = {
["margin"] = 10,
["grow_direction"] = "RIGHT",
},
["Resto"] = {
["margin"] = 10,
["grow_direction"] = "RIGHT",
},
},
["bigicon_enabled"] = {
["Modern"] = true,
["Coor_2027"] = false,
["2026_quazii"] = true,
["Resto"] = true,
},
["timeline_frame"] = {
["Modern"] = {
["travel_direction"] = "VERTICAL",
["point"] = "CENTER",
["ticks_enabled"] = true,
["timeline_texture_color"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["y"] = 110,
["x"] = 410,
["travelSize"] = 500,
["otherSize"] = 50,
["timeline_texture"] = "Blizzard Dialog Background",
["horizontal"] = false,
["inverse_travel_direction"] = false,
["iconMargin"] = 5,
},
["Coor_2027"] = {
["travel_direction"] = "VERTICAL",
["point"] = "TOP",
["ticks_enabled"] = true,
["timeline_texture_color"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["y"] = -47.25,
["x"] = 551.75048828125,
["travelSize"] = 500,
["otherSize"] = 1,
["timeline_texture"] = "Blizzard Dialog Background",
["horizontal"] = false,
["inverse_travel_direction"] = false,
["iconMargin"] = 3,
},
["2026_quazii"] = {
["travel_direction"] = "VERTICAL",
["point"] = "CENTER",
["ticks_enabled"] = true,
["timeline_texture_color"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["y"] = 110,
["x"] = 410,
["travelSize"] = 500,
["otherSize"] = 50,
["timeline_texture"] = "Blizzard Dialog Background",
["horizontal"] = false,
["inverse_travel_direction"] = false,
["iconMargin"] = 5,
},
["Resto"] = {
["travel_direction"] = "VERTICAL",
["point"] = "CENTER",
["ticks_enabled"] = true,
["timeline_texture_color"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["y"] = 110,
["x"] = 410,
["travelSize"] = 500,
["otherSize"] = 50,
["timeline_texture"] = "Blizzard Dialog Background",
["horizontal"] = false,
["inverse_travel_direction"] = false,
["iconMargin"] = 5,
},
},
["text_highlight"] = {
["Modern"] = {
["margin"] = 5,
["grow_direction"] = "UP",
},
["Coor_2027"] = {
["margin"] = 5,
["grow_direction"] = "UP",
},
["2026_quazii"] = {
["margin"] = 5,
["grow_direction"] = "UP",
},
["Resto"] = {
["margin"] = 5,
["grow_direction"] = "UP",
},
},
["bigicon_frame"] = {
["Modern"] = {
["y"] = -200,
["x"] = 410,
["point"] = "CENTER",
},
["Coor_2027"] = {
["y"] = -98.25006103515625,
["x"] = -509,
["point"] = "TOPRIGHT",
},
["2026_quazii"] = {
["y"] = -200,
["x"] = 410,
["point"] = "CENTER",
},
["Resto"] = {
["y"] = -200,
["x"] = 410,
["point"] = "CENTER",
},
},
["text_highlight_enabled"] = {
["Modern"] = true,
["Coor_2027"] = true,
["2026_quazii"] = true,
["Resto"] = true,
},
},
["profiles"] = {
["Default"] = {
["big_icon_text_settings"] = {
["backgroundTexture"] = "Blizzard Dialog Background",
["fontFlag"] = {
["OUTLINE"] = true,
},
["enableShadow"] = true,
["useBackground"] = false,
["font"] = "Friz Quadrata TT",
["backgroundTextureOffset"] = {
["y"] = 0,
["x"] = 0,
},
["fontSize"] = 20,
["text_anchor"] = "BOTTOM",
["defaultColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
},
["disableBossModsEmphasisedBars"] = true,
["text_settings"] = {
["fontSize"] = 14,
["fontFlag"] = {
["OUTLINE"] = true,
},
["enableShadow"] = true,
["useBackground"] = false,
["font"] = "quazii",
["backgroundTextureOffset"] = {
["y"] = 10,
["x"] = 10,
},
["backgroundTexture"] = "Blizzard Dialog Background",
["defaultColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["text_anchor"] = "LEFT",
["useEventColor"] = true,
},
["cooldown_settings"] = {
["cooldown_color"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["fontSize"] = 24,
["font"] = "quazii",
["cooldown_highlight"] = {
["enabled"] = true,
["highlights"] = {
{
["glowColor"] = {
["a"] = 1,
["r"] = 0.95,
["g"] = 0.95,
["b"] = 0.32,
},
["time"] = 3,
["glowType"] = "PROC",
["color"] = {
["r"] = 1,
["g"] = 0,
["b"] = 0,
},
["useGlow"] = false,
},
{
["glowColor"] = {
["a"] = 1,
["r"] = 0.95,
["g"] = 0.95,
["b"] = 0.32,
},
["time"] = 5,
["glowType"] = "PROC",
["color"] = {
["r"] = 1,
["g"] = 1,
["b"] = 0,
},
["useGlow"] = false,
},
},
},
},
["reminders"] = {
},
["editor"] = {
["defaultEncounterDuration"] = 300,
},
["big_icon_settings"] = {
["zoom"] = 0.3,
["size"] = 100,
["TextOffset"] = {
["y"] = 10,
["x"] = 0,
},
["dangerIcon"] = true,
["useTooltip"] = 0,
["dispellIcons"] = true,
["dispellBorders"] = true,
},
["importMergeMode"] = true,
["disableBossModsBars"] = true,
["highlight_text_settings"] = {
["strata"] = "FULLSCREEN",
["dispellIcons"] = true,
["useBackground"] = false,
["font"] = "Friz Quadrata TT",
["backgroundTextureOffset"] = {
["y"] = 0,
["x"] = 0,
},
["enableShadow"] = true,
["backgroundTexture"] = "Blizzard Dialog Background",
["defaultColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["fontSize"] = 14,
},
["icon_settings"] = {
["zoom"] = 0.3,
["border"] = "dispell",
["useTooltip"] = 0,
["roleIcons"] = true,
["dangerIcon"] = true,
["dispellIcons"] = true,
["TextOffset"] = {
["y"] = 0,
["x"] = 16,
},
["strata"] = "FULLSCREEN",
["size"] = 44,
},
["importRelevant"] = true,
["dispellTextColor"] = true,
},
},
}
