
XIVBarDB = {
["char"] = {
["Decoran - Draenor"] = {
["portItem"] = {
["portId"] = 140192,
["text"] = "Dalaran Hearthstone",
},
},
["Nothree - Draenor"] = {
["portItem"] = {
["text"] = "Dalaran Hearthstone",
["portId"] = 140192,
},
},
["Corzumo - Stormrage"] = {
["portItem"] = {
["text"] = "Dalaran Hearthstone",
["portId"] = 140192,
},
},
["Abaray - Draenor"] = {
["portItem"] = {
["text"] = "Dalaran Hearthstone",
["portId"] = 140192,
},
},
["Unlockit - Draenor"] = {
["portItem"] = {
["text"] = "Dalaran Hearthstone",
["portId"] = 140192,
},
},
["Corry - Draenor"] = {
["portItem"] = {
["portId"] = 140192,
["text"] = "Dalaran Hearthstone",
},
},
["Cooriam - Draenor"] = {
["portItem"] = {
["portId"] = 110560,
},
},
["Altoki - Draenor"] = {
["portItem"] = {
["text"] = "Dalaran Hearthstone",
["portId"] = 140192,
},
},
["Coorios - Draenor"] = {
["portItem"] = {
["portId"] = 140192,
["text"] = "Dalaran Hearthstone",
},
},
["Gembank - Stormrage"] = {
["portItem"] = {
["portId"] = 140192,
["text"] = "Dalaran Hearthstone",
},
},
["Corwing - Draenor"] = {
["portItem"] = {
["portId"] = 140192,
["text"] = "Dalaran Hearthstone",
},
},
["Coorlan - Draenor"] = {
["portItem"] = {
["portId"] = 140192,
["text"] = "Dalaran Hearthstone",
},
},
["Corzos - Draenor"] = {
["portItem"] = {
["portId"] = 140192,
["text"] = "Dalaran Hearthstone",
},
},
["Corsell - Draenor"] = {
["portItem"] = {
["portId"] = 140192,
["text"] = "Dalaran Hearthstone",
},
},
["Corra - Draenor"] = {
["portItem"] = {
["portId"] = 140192,
["text"] = "Dalaran Hearthstone",
},
},
["Decor - Draenor"] = {
["portItem"] = {
["text"] = "Dalaran Hearthstone",
["portId"] = 140192,
},
},
["Coriiam - Draenor"] = {
["portItem"] = {
["portId"] = 140192,
["text"] = "Dalaran Hearthstone",
},
},
["Faile - Stormrage"] = {
["portItem"] = {
["portId"] = 140192,
["text"] = "Dalaran Hearthstone",
},
},
["Sedore - Draenor"] = {
["portItem"] = {
["portId"] = 140192,
["text"] = "Dalaran Hearthstone",
},
},
["Corzumo - Draenor"] = {
["portItem"] = {
["portId"] = 140192,
["text"] = "Dalaran Hearthstone",
},
},
["Corpy - Draenor"] = {
["portItem"] = {
["text"] = "Dalaran Hearthstone",
["portId"] = 140192,
},
},
},
["profileKeys"] = {
["Decoran - Draenor"] = "Default",
["Nothree - Draenor"] = "Default",
["Corzumo - Stormrage"] = "Default",
["Abaray - Draenor"] = "Default",
["Unlockit - Draenor"] = "Default",
["Corry - Draenor"] = "Default",
["Cooriam - Draenor"] = "Default",
["Altoki - Draenor"] = "Default",
["Coorios - Draenor"] = "Default",
["Gembank - Stormrage"] = "Default",
["Corwing - Draenor"] = "Default",
["Coorlan - Draenor"] = "Default",
["Corzos - Draenor"] = "Default",
["Corsell - Draenor"] = "Default",
["Corra - Draenor"] = "Default",
["Decor - Draenor"] = "Default",
["Coriiam - Draenor"] = "Default",
["Faile - Stormrage"] = "Default",
["Sedore - Draenor"] = "Default",
["Corzumo - Draenor"] = "Default",
["Corpy - Draenor"] = "Default",
},
["global"] = {
["characters"] = {
["Corzumo-Stormrage"] = {
["dailyMoney"] = -1766986,
["sessionMoney"] = 4170,
["faction"] = "Horde",
["lastLoginDate"] = 20260420,
["class"] = "ROGUE",
["currentMoney"] = 6221563,
["realm"] = "Stormrage",
},
["Coriiam-Draenor"] = {
["dailyMoney"] = 400,
["faction"] = "Alliance",
["sessionMoney"] = 400,
["currentMoney"] = 10400,
["class"] = "DEMONHUNTER",
["lastLoginDate"] = 20260327,
["realm"] = "Draenor",
},
["Corry-Draenor"] = {
["dailyMoney"] = 0,
["faction"] = "Horde",
["sessionMoney"] = 0,
["currentMoney"] = 292251758,
["class"] = "ROGUE",
["lastLoginDate"] = 20260420,
["realm"] = "Draenor",
},
["Corpy-Draenor"] = {
["dailyMoney"] = 0,
["sessionMoney"] = 0,
["faction"] = "Horde",
["lastLoginDate"] = 20260409,
["class"] = "MAGE",
["currentMoney"] = 10000,
["realm"] = "Draenor",
},
["Corwing-Draenor"] = {
["dailyMoney"] = 44505,
["faction"] = "Horde",
["sessionMoney"] = 44505,
["currentMoney"] = 44505,
["class"] = "EVOKER",
["lastLoginDate"] = 20260417,
["realm"] = "Draenor",
},
["Faile-Stormrage"] = {
["dailyMoney"] = 0,
["faction"] = "Alliance",
["sessionMoney"] = 0,
["currentMoney"] = 91487297,
["class"] = "PALADIN",
["lastLoginDate"] = 20260415,
["realm"] = "Stormrage",
},
["Coorios-Draenor"] = {
["dailyMoney"] = 0,
["faction"] = "Alliance",
["sessionMoney"] = 0,
["currentMoney"] = 10000,
["class"] = "DRUID",
["lastLoginDate"] = 20260323,
["realm"] = "Draenor",
},
["Decor-Draenor"] = {
["dailyMoney"] = 0,
["sessionMoney"] = 0,
["faction"] = "Horde",
["lastLoginDate"] = 20260415,
["class"] = "WARLOCK",
["currentMoney"] = 3372268,
["realm"] = "Draenor",
},
["Cooriam-Draenor"] = {
["dailyMoney"] = 181314686,
["sessionMoney"] = 181314686,
["faction"] = "Horde",
["lastLoginDate"] = 20260421,
["class"] = "MONK",
["currentMoney"] = 3678511896,
["realm"] = "Draenor",
},
["Altoki-Draenor"] = {
["dailyMoney"] = 0,
["sessionMoney"] = 0,
["faction"] = "Horde",
["lastLoginDate"] = 20260415,
["class"] = "SHAMAN",
["currentMoney"] = 704661257,
["realm"] = "Draenor",
},
["Corsell-Draenor"] = {
["dailyMoney"] = -290000000,
["faction"] = "Horde",
["sessionMoney"] = -290000000,
["currentMoney"] = 3490737,
["class"] = "ROGUE",
["lastLoginDate"] = 20260415,
["realm"] = "Draenor",
},
["Unlockit-Draenor"] = {
["dailyMoney"] = 0,
["sessionMoney"] = 0,
["faction"] = "Horde",
["lastLoginDate"] = 20260420,
["class"] = "DRUID",
["currentMoney"] = 0,
["realm"] = "Draenor",
},
["Nothree-Draenor"] = {
["dailyMoney"] = 719,
["sessionMoney"] = 719,
["faction"] = "Alliance",
["lastLoginDate"] = 19990000,
["class"] = "ROGUE",
["currentMoney"] = 719,
["realm"] = "Draenor",
},
["Decoran-Draenor"] = {
["dailyMoney"] = -4268171,
["faction"] = "Horde",
["sessionMoney"] = 0,
["currentMoney"] = 15835258,
["class"] = "WARLOCK",
["lastLoginDate"] = 20260419,
["realm"] = "Draenor",
},
["Coorlan-Draenor"] = {
["dailyMoney"] = 2982200,
["faction"] = "Horde",
["sessionMoney"] = 2982200,
["currentMoney"] = 850576416,
["class"] = "WARRIOR",
["lastLoginDate"] = 20260421,
["realm"] = "Draenor",
},
["Gembank-Stormrage"] = {
["dailyMoney"] = 0,
["faction"] = "Horde",
["sessionMoney"] = 0,
["currentMoney"] = 5591497,
["class"] = "MAGE",
["lastLoginDate"] = 20260415,
["realm"] = "Stormrage",
},
["Abaray-Draenor"] = {
["dailyMoney"] = -2906232,
["sessionMoney"] = -4414725,
["faction"] = "Horde",
["lastLoginDate"] = 20260420,
["class"] = "DRUID",
["currentMoney"] = 368138517,
["realm"] = "Draenor",
},
["Corra-Draenor"] = {
["dailyMoney"] = -165696,
["faction"] = "Alliance",
["sessionMoney"] = -165696,
["currentMoney"] = 142419400,
["class"] = "HUNTER",
["lastLoginDate"] = 20260420,
["realm"] = "Draenor",
},
["Sedore-Draenor"] = {
["dailyMoney"] = 2890415,
["faction"] = "Horde",
["sessionMoney"] = 2890415,
["currentMoney"] = 1259930938,
["class"] = "PRIEST",
["lastLoginDate"] = 20260420,
["realm"] = "Draenor",
},
["Corzumo-Draenor"] = {
["dailyMoney"] = 10001420,
["faction"] = "Horde",
["sessionMoney"] = 10001420,
["currentMoney"] = 10001420,
["class"] = "ROGUE",
["lastLoginDate"] = 20260421,
["realm"] = "Draenor",
},
["Corzos-Draenor"] = {
["dailyMoney"] = 10002217,
["faction"] = "Horde",
["sessionMoney"] = 1517,
["currentMoney"] = 10012217,
["class"] = "ROGUE",
["lastLoginDate"] = 20260421,
["realm"] = "Draenor",
},
},
},
["profiles"] = {
["Default"] = {
["selectedHouseGuid"] = "Opaque-1",
["selectedHearthstones"] = {
},
["general"] = {
["enableFreePlacement"] = true,
["yOffset"] = -526,
["barFullscreen"] = false,
["moduleSpacing"] = 26,
["freePlacementInitialized"] = true,
["modulePlacements"] = {
["tradeskill"] = {
["anchorPoint"] = "CENTER",
["x"] = -607,
["initialX"] = 147.666748046875,
["initialAnchorPoint"] = "CENTER",
["captured"] = true,
},
["talent"] = {
["anchorPoint"] = "CENTER",
["x"] = -848,
["initialX"] = -109.2498779296875,
["initialAnchorPoint"] = "CENTER",
["captured"] = true,
},
["reputation"] = {
["anchorPoint"] = "LEFT",
["x"] = 1,
["initialX"] = 1,
["initialAnchorPoint"] = "LEFT",
["captured"] = true,
},
["travel"] = {
["anchorPoint"] = "RIGHT",
["x"] = -124,
["initialX"] = -1,
["initialAnchorPoint"] = "RIGHT",
["captured"] = true,
},
["microMenu"] = {
["anchorPoint"] = "LEFT",
["x"] = 1,
["initialX"] = 1,
["initialAnchorPoint"] = "LEFT",
["captured"] = true,
},
["vault"] = {
["anchorPoint"] = "RIGHT",
["x"] = -1,
["initialX"] = -1,
["initialAnchorPoint"] = "RIGHT",
["captured"] = true,
},
["currency"] = {
["anchorPoint"] = "CENTER",
["x"] = 316.5836181640625,
["initialX"] = 315.583251953125,
["initialAnchorPoint"] = "CENTER",
["captured"] = true,
},
["gold"] = {
["anchorPoint"] = "RIGHT",
["x"] = -1119,
["initialX"] = -295,
["initialAnchorPoint"] = "RIGHT",
["captured"] = true,
},
["clock"] = {
["anchorPoint"] = "CENTER",
["x"] = 0,
["initialX"] = 0,
["initialAnchorPoint"] = "CENTER",
["captured"] = true,
},
["MasterVolume"] = {
["anchorPoint"] = "LEFT",
["x"] = 1,
["initialX"] = 1,
["initialAnchorPoint"] = "LEFT",
["captured"] = true,
},
["armor"] = {
["anchorPoint"] = "LEFT",
["x"] = 3,
["initialX"] = 0,
["initialAnchorPoint"] = "LEFT",
["captured"] = false,
},
["system"] = {
["anchorPoint"] = "CENTER",
["x"] = 279,
["initialX"] = 406.1666259765625,
["initialAnchorPoint"] = "CENTER",
["captured"] = true,
},
},
["barPadding"] = 0,
},
["color"] = {
["barColor"] = {
["r"] = 0,
["g"] = 0.08627451211214066,
["b"] = 0.05098039656877518,
},
},
["hideAdditionalTooltipText"] = true,
["hearthstonesList"] = {
[208704] = "Deepdweller's Earthen Hearthstone",
[180290] = "Night Fae Hearthstone",
[172179] = "Eternal Traveler's Hearthstone",
},
["modules"] = {
["talent"] = {
["loadoutSwitcherEnabled"] = false,
},
["microMenu"] = {
["spellMergedIntoTalent"] = true,
["enabled"] = false,
},
["armor"] = {
["enabled"] = false,
},
},
["hideHearthstoneButton"] = false,
["hearthstoneCache"] = {
[208704] = "Deepdweller's Earthen Hearthstone",
[172179] = "Eternal Traveler's Hearthstone",
[180290] = "Night Fae Hearthstone",
[6948] = "Hearthstone",
},
["enableMythicPortals"] = true,
["text"] = {
["flags"] = 2,
["fontSize"] = 15,
["font"] = "quazii",
},
["hidePortButton"] = false,
},
},
}
