
Details_StreamerDB = {
["characters"] = {
["Decoran - Draenor"] = "Cooriam - Draenor",
["Corzos - Draenor"] = "Cooriam - Draenor",
["Gembank - Stormrage"] = "Cooriam - Draenor",
["Corwing - Draenor"] = "Cooriam - Draenor",
["Coorlan - Draenor"] = "Cooriam - Draenor",
["Corzumo - Draenor"] = "Cooriam - Draenor",
["Abaray - Draenor"] = "Cooriam - Draenor",
["Nothree - Draenor"] = "Cooriam - Draenor",
["Corzumo - Stormrage"] = "Cooriam - Draenor",
["Corra - Draenor"] = "Cooriam - Draenor",
["Unlockit - Draenor"] = "Cooriam - Draenor",
["Corry - Draenor"] = "Cooriam - Draenor",
["Sedore - Draenor"] = "Cooriam - Draenor",
["Cooriam - Draenor"] = "Cooriam - Draenor",
["Corpy - Draenor"] = "Cooriam - Draenor",
},
["profiles"] = {
["Cooriam - Draenor"] = {
["use_square_mode"] = false,
["is_first_run"] = false,
["arrow_color"] = {
1,
1,
1,
0.5,
},
["main_frame_size"] = {
299.9999694824219,
499.9999694824219,
},
["arrow_anchor_y"] = 0,
["minimap"] = {
["minimapPos"] = 160,
["radius"] = 160,
["hide"] = false,
},
["main_frame_locked"] = false,
["arrow_anchor_x"] = 0,
["author"] = "Terciob",
["row_texture"] = "Details Serenity",
["square_grow_direction"] = "right",
["font_size"] = 10,
["row_color"] = {
0.1,
0.1,
0.1,
0.4,
},
["square_amount"] = 5,
["enabled"] = false,
["arrow_size"] = 10,
["use_spark"] = true,
["row_spacement"] = 21,
["main_frame_color"] = {
0,
0,
0,
0.2,
},
["main_frame_strata"] = "LOW",
["arrow_texture"] = "Interface\\CHATFRAME\\ChatFrameExpandArrow",
["per_second"] = {
["enabled"] = false,
["point"] = "CENTER",
["scale"] = 1,
["font_shadow"] = true,
["y"] = 0,
["x"] = 6.103515625e-05,
["attribute_type"] = 1,
["update_speed"] = 0.05,
["size"] = 32,
},
["y"] = -4.57763671875e-05,
["x"] = 0,
["font_face"] = "Friz Quadrata TT",
["square_size"] = 32,
["point"] = "CENTER",
["font_color"] = {
1,
1,
1,
1,
},
["row_height"] = 20,
["scale"] = 1,
},
},
}
